### ISSUE TITLE
List items are not rendered while scrolling

### ISSUE THREAD

**Issue by pablomaurer** [anagram4wander/ng-vfor-lib#2]
**Describe the bug**
List items are not rendered while scrolling. So you have to stop scrolling, to see where you're at.

**To Reproduce**
Did download this repository and run ng serve

**Expected behavior**
Seeing what you are scrolling.

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Chrome

![sample](https://user-images.githubusercontent.com/2413156/46175755-55d5b600-c2ad-11e8-9b35-c08f55e9dac8.gif)

**Comment by anagram4wander** [comment]
Interesting, not seeing this on windows, my guess is it’s something to do with the throttled part on the scroll event. I will take a look at that once I can grab a spare MacBook to reproduce it.

**Comment by anagram4wander** [comment]
I think it was the use of settimeout rather than using zone.runoutsideofangular. Changed that.. let me know if that fixes it for you.
